### ISSUE TITLE
Error installing this app

### ISSUE THREAD

**Issue by thebarty** [xolvio/Letterpress#18]
Hi guys,

I am having problems getting this to run on OSX 10.10.5 with javac (`javac 1.8.0_65`) installed.

I simply did a `git clone` and `./run.sh`, BUT **I am getting an error.**
Trying to fix it I also installed chimp via npm using `a sudo npm install chimp`,
but it did not help.

This is the error I am getting:

```
Error: EACCES, mkdir '/Users/myaccount/.meteor/packages/velocity_meteor-tool/.build932656..1.1.4_2.strfyk++os.osx.x86_64+web.browser+web.cordova'
    at Object.Future.wait (/Users/myaccount/.meteor/packages/meteor-tool/.1.1.10.1euvgy9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:398:15)
    at /tools/fs/files.js:1331:28
    at Object.wrapper [as mkdir] (/tools/fs/files.js:1334:20)
    at Object.files.mkdir_p (/tools/fs/files.js:405:11)
    at new Builder (/tools/isobuild/builder.js:85:13)
    at [object Object]._.extend.saveToPath (/tools/isobuild/isopack.js:1155:19)
    at [object Object]._.extend._saveIsopack (/tools/packaging/tropohouse.js:366:15)
    at /tools/packaging/tropohouse.js:506:14
    at /tools/utils/buildmessage.js:356:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:349:34
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:347:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at Object.enterJob (/tools/utils/buildmessage.js:321:26)
    at Object.download (/tools/packaging/tropohouse.js:437:20)
    at /tools/packaging/tropohouse.js:575:22
    at /tools/utils/buildmessage.js:356:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:349:34
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:347:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at Object.enterJob (/tools/utils/buildmessage.js:321:26)
    at [object Object]._.extend.downloadPackagesMissingFromMap (/tools/packaging/tropohouse.js:572:20)
    at /tools/cli/main.js:431:30
    at /tools/packaging/catalog/catalog.js:100:5
    at /tools/utils/buildmessage.js:268:13
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:261:29
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:259:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:250:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at Object.capture (/tools/utils/buildmessage.js:249:19)
    at Object.catalog.runAndRetryWithRefreshIfHelpful (/tools/packaging/catalog/catalog.js:99:31)
    at /tools/cli/main.js:430:17
    at /tools/utils/buildmessage.js:268:13
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:261:29
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:259:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:250:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at Object.capture (/tools/utils/buildmessage.js:249:19)
    at /tools/cli/main.js:428:33
    at [object Object]._.extend.withProgressDisplayVisible (/tools/console/console.js:611:14)
    at springboard (/tools/cli/main.js:427:11)
    at /tools/cli/main.js:1028:5
```

Any ideas whats wrong?

**Comment by SamHatoum** [comment]
you probably don't want to do `sudo`. It looks like something is up with your user account's rights to write files. Try blowing the entire `/Users/myaccount/.meteor` directory and starting again, not using sudo anywhere

**Comment by thebarty** [comment]
@samhatoum thanks for the quick respone.

I removed `~/.meteor` in my home-directory and still get the same error.

Do I need to run `npm install chimp` at all in order to get cucumber running, or does cucumber install this with adding `xolvio:cucumber` to the meteor project?

**Comment by SamHatoum** [comment]
The latter, you just need to add `xolvio:cucumber` that's all

Can you try to create a new project and add `sanjo:jasmine` and see how that works?
Then again, a new project and add `xolvio:cucumber` and let me know if you get the same result

**Comment by thebarty** [comment]
@sam: Thanks for the quick feedback.

OK I gave both options a try and had NO luck...

**TEST 1) "pure xolvio:cucumber installation"**

```
meteor create cucumber-test;
cd cucumber-test;
meteor add xolvio:cucumber;
meteor update;
```

results in this:

```
=> Using velocity:METEOR@1.2.0.2_1 as requested (overriding Meteor 1.2.1)

[[[[[ ~/MeteorProjekte/tester-cucubmer ]]]]]

=> Started proxy.

Changes to your project's package version selections:

autoupdate              downgraded from 1.2.4 to 1.2.3
check                   downgraded from 1.1.0 to 1.0.6
coffeescript            downgraded from 1.0.11 to 1.0.10
ddp-common              downgraded from 1.2.2 to 1.2.1
ddp-server              downgraded from 1.2.2 to 1.2.1
ecmascript              downgraded from 0.1.6 to 0.1.5
ecmascript-collections  added, version 0.1.6
ecmascript-runtime      removed from your project
es5-shim                downgraded from 4.1.14 to 4.1.13
less                    downgraded from 2.5.1 to 2.5.0_3
meteor                  downgraded from 1.1.10 to 1.1.9
mongo                   downgraded from 1.1.3 to 1.1.2
promise                 downgraded from 0.5.1 to 0.5.0
random                  downgraded from 1.0.5 to 1.0.4
reactive-dict           downgraded from 1.1.3 to 1.1.2
standard-minifiers      downgraded from 1.0.2 to 1.0.1
templating              downgraded from 1.1.5 to 1.1.4
webapp                  downgraded from 1.2.3 to 1.2.2

** You've set up some data subscriptions with Meteor.publish(), but
** you still have autopublish turned on. Because autopublish is still
** on, your Meteor.publish() calls won't have much effect. All data
** will still be sent to all clients.
**
** Turn off autopublish by removing the autopublish package:
**
**   $ meteor remove autopublish
**
** .. and make sure you have Meteor.publish() and Meteor.subscribe() calls
** for each collection that you want clients to see.

=> Started your app.

=> App running at: http://localhost:50702/
[velocity] Mirror has established connection with Velocity.
[xolvio:cucumber] Cucumber is running
[chimp][hooks] BeforeFeatures hook had error
{ [Error: Unable to find a free port] message: 'Unable to find a free port', type: 'RuntimeError' }
Error: Unable to find a free port
  at Object.Future.wait (/Users/myaccount/.meteor/packages/xolvio_cucumber/.0.19.4_1.u4ev2v++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/chimp/node_modules/fibers/future.js:420:15)
  at Object.<anonymous> (/Users/myaccount/.meteor/packages/xolvio_cucumber/.0.19.4_1.u4ev2v++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/chimp/node_modules/xolvio-sync-webdriverio/node_modules/xolvio-fiber-utils/index.js:48:19)
  at Object.<anonymous> (/Users/myaccount/.meteor/packages/xolvio_cucumber/.0.19.4_1.u4ev2v++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/chimp/lib/session-manager.js:137:21)
  at initBrowser (/Users/myaccount/.meteor/packages/xolvio_cucumber/.0.19.4_1.u4ev2v++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/chimp/lib/cucumberjs/world-helper.js:149:15)
  at Object.worldHelper.setupBrowserAndDDP (/Users/myaccount/.meteor/packages/xolvio_cucumber/.0.19.4_1.u4ev2v++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/chimp/lib/cucumberjs/world-helper.js:191:7)
  at /Users/myaccount/.meteor/packages/xolvio_cucumber/.0.19.4_1.u4ev2v++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/chimp/lib/cucumberjs/hooks.js:8:17
  at /Users/myaccount/.meteor/packages/xolvio_cucumber/.0.19.4_1.u4ev2v++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/chimp/lib/cucumber-wrapper.js:114:43

    - - - - -
  at new ErrorHandler.RuntimeError (/Users/myaccount/.meteor/packages/xolvio_cucumber/.0.19.4_1.u4ev2v++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/chimp/node_modules/xolvio-sync-webdriverio/node_modules/webdriverio/lib/utils/ErrorHandler.js:92:12)
  at RequestHandler.<anonymous> (/Users/myaccount/.meteor/packages/xolvio_cucumber/.0.19.4_1.u4ev2v++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/chimp/node_modules/xolvio-sync-webdriverio/node_modules/webdriverio/lib/utils/RequestHandler.js:138:25)
  at Request.self.callback (/Users/myaccount/.meteor/packages/xolvio_cucumber/.0.19.4_1.u4ev2v++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/chimp/node_modules/xolvio-sync-webdriverio/node_modules/webdriverio/node_modules/request/request.js:373:22)
  at Request.emit (events.js:98:17)
  at Request.<anonymous> (/Users/myaccount/.meteor/packages/xolvio_cucumber/.0.19.4_1.u4ev2v++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/chimp/node_modules/xolvio-sync-webdriverio/node_modules/webdriverio/node_modules/request/request.js:1318:14)
  at Request.emit (events.js:117:20)
  at IncomingMessage.<anonymous> (/Users/myaccount/.meteor/packages/xolvio_cucumber/.0.19.4_1.u4ev2v++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/chimp/node_modules/xolvio-sync-webdriverio/node_modules/webdriverio/node_modules/request/request.js:1266:12)
  at IncomingMessage.emit (events.js:117:20)
  at _stream_readable.js:944:16
  at process._tickDomainCallback (node.js:492:13)

[chimp] Finished running async processes with errors
[chimp] run complete with errors Cucumber steps failed
[chimp] Could not get Cucumber Results from run result:
[ undefined, [ undefined, null ] ]
[xolvio:cucumber] Bad response from Chimp server.
{ statusCode: 200,
  content: '',
  headers: 
   { 'content-type': 'application/json; charset=utf-8',
     'cache-control': 'no-cache',
     'content-length': '0',
     date: 'Sat, 31 Oct 2015 11:08:04 GMT',
     connection: 'keep-alive' },
  data: null }
```

**TEST 2) "sanjo:jasmine" + "xolvio:cucumber"**

```
meteor create cucumber-test2;
cd cucumber-test2;
meteor add sanjo:jasmine;
meteor add xolvio:cucumber;
meteor update;
```

this is the tail:

```
[xolvio:cucumber] Bad response from Chimp server.
{ statusCode: 200,
  content: '',
  headers: 
   { 'content-type': 'application/json; charset=utf-8',
     'cache-control': 'no-cache',
     'content-length': '0',
     date: 'Sat, 31 Oct 2015 12:25:51 GMT',
     connection: 'keep-alive' },
  data: null }
[xolvio:cucumber] Cucumber is running
[chimp][hooks] BeforeFeatures hook had error
{ [Error: Unable to find a free port] message: 'Unable to find a free port', type: 'RuntimeError' }
Error: Unable to find a free port
  at Object.Future.wait (/Users/myaccount/.meteor/packages/xolvio_cucumber/.0.19.4_1.u4ev2v++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/chimp/node_modules/fibers/future.js:420:15)
  at Object.<anonymous> (/Users/myaccount/.meteor/packages/xolvio_cucumber/.0.19.4_1.u4ev2v++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/chimp/node_modules/xolvio-sync-webdriverio/node_modules/xolvio-fiber-utils/index.js:48:19)
  at Object.<anonymous> (/Users/myaccount/.meteor/packages/xolvio_cucumber/.0.19.4_1.u4ev2v++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/chimp/lib/session-manager.js:137:21)
  at initBrowser (/Users/myaccount/.meteor/packages/xolvio_cucumber/.0.19.4_1.u4ev2v++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/chimp/lib/cucumberjs/world-helper.js:149:15)
  at Object.worldHelper.setupBrowserAndDDP (/Users/myaccount/.meteor/packages/xolvio_cucumber/.0.19.4_1.u4ev2v++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/chimp/lib/cucumberjs/world-helper.js:191:7)
  at /Users/myaccount/.meteor/packages/xolvio_cucumber/.0.19.4_1.u4ev2v++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/chimp/lib/cucumberjs/hooks.js:8:17
  at /Users/myaccount/.meteor/packages/xolvio_cucumber/.0.19.4_1.u4ev2v++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/chimp/lib/cucumber-wrapper.js:114:43

    - - - - -
  at new ErrorHandler.RuntimeError (/Users/myaccount/.meteor/packages/xolvio_cucumber/.0.19.4_1.u4ev2v++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/chimp/node_modules/xolvio-sync-webdriverio/node_modules/webdriverio/lib/utils/ErrorHandler.js:92:12)
  at RequestHandler.<anonymous> (/Users/myaccount/.meteor/packages/xolvio_cucumber/.0.19.4_1.u4ev2v++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/chimp/node_modules/xolvio-sync-webdriverio/node_modules/webdriverio/lib/utils/RequestHandler.js:138:25)
  at Request.self.callback (/Users/myaccount/.meteor/packages/xolvio_cucumber/.0.19.4_1.u4ev2v++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/chimp/node_modules/xolvio-sync-webdriverio/node_modules/webdriverio/node_modules/request/request.js:373:22)
  at Request.emit (events.js:98:17)
  at Request.<anonymous> (/Users/myaccount/.meteor/packages/xolvio_cucumber/.0.19.4_1.u4ev2v++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/chimp/node_modules/xolvio-sync-webdriverio/node_modules/webdriverio/node_modules/request/request.js:1318:14)
  at Request.emit (events.js:117:20)
  at IncomingMessage.<anonymous> (/Users/myaccount/.meteor/packages/xolvio_cucumber/.0.19.4_1.u4ev2v++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/chimp/node_modules/xolvio-sync-webdriverio/node_modules/webdriverio/node_modules/request/request.js:1266:12)
  at IncomingMessage.emit (events.js:117:20)
  at _stream_readable.js:944:16
  at process._tickDomainCallback (node.js:492:13)

[chimp] Finished running async processes with errors
[chimp] run complete with errors Cucumber steps failed
[chimp] Could not get Cucumber Results from run result:
[ undefined, [ null ] ]
[xolvio:cucumber] Bad response from Chimp server.
{ statusCode: 200,
  content: '',
  headers: 
   { 'content-type': 'application/json; charset=utf-8',
     'cache-control': 'no-cache',
     'content-length': '0',
     date: 'Sat, 31 Oct 2015 12:26:42 GMT',
     connection: 'keep-alive' },
  data: null }
```
