### ISSUE TITLE
Letterpress crashes immediately

### ISSUE THREAD

**Issue by fulv** [xolvio/Letterpress#5]
Clone this repo and run `meteor` inside it, it will not take you very far (see trace below).

Is there some version incompatibility?

```
W20150710-17:09:19.392(-7)? (STDERR)
W20150710-17:09:19.392(-7)? (STDERR) /Users/fulvio/.meteor/packages/meteor-tool/.1.1.3.1f82d1e++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20150710-17:09:19.392(-7)? (STDERR) 						throw(ex);
W20150710-17:09:19.392(-7)? (STDERR) 						      ^
W20150710-17:09:19.394(-7)? (STDERR) TypeError: Cannot read property 'stripe' of undefined
W20150710-17:09:19.394(-7)? (STDERR)   at app/server/stripe.js:1:78
W20150710-17:09:19.394(-7)? (STDERR)   at app/server/stripe.js:30:3
W20150710-17:09:19.394(-7)? (STDERR)   at /private/tmp/meteorenv/Letterpress/Letterpress/.meteor/local/build/programs/server/boot.js:222:10
W20150710-17:09:19.394(-7)? (STDERR)   at Array.forEach (native)
W20150710-17:09:19.394(-7)? (STDERR)   at Function._.each._.forEach (/Users/fulvio/.meteor/packages/meteor-tool/.1.1.3.1f82d1e++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20150710-17:09:19.394(-7)? (STDERR)   at /private/tmp/meteorenv/Letterpress/Letterpress/.meteor/local/build/programs/server/boot.js:117:5
W20150710-17:09:19.394(-7)? (STDERR)
=> Exited with code: 8
=> Your application is crashing. Waiting for file change.
```

**Comment by samhatoum** [comment]
try with `meteor --settings settings.json`

**Comment by fulv** [comment]
That did the trick!
Thanks!

**Comment by hudat** [comment]
The "meteor --settings settings.json" solved the stripe TypeError for me, however, I ran into this error:

While preparing to run:
   settings.json: file not found (settings file)

**Comment by samhatoum** [comment]
the settings file is not on the root, see run.sh

**Comment by hudat** [comment]
Ah, that did it. Thanks man!!
